/* automatically generated from xfwm4-tweaks-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tweaks_dialog_ui)
#endif
#ifdef __GNUC__
static const char tweaks_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tweaks_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kAdjustment\" id=\"adjustment1\"><property name=\"upper\">100</property"
  "><property name=\"value\">75</property><property name=\"step_increment\""
  ">1</property><property name=\"page_increment\">10</property></object><o"
  "bject class=\"GtkAdjustment\" id=\"adjustment2\"><property name=\"upper"
  "\">100</property><property name=\"value\">90</property><property name=\""
  "step_increment\">1</property><property name=\"page_increment\">10</prop"
  "erty></object><object class=\"GtkAdjustment\" id=\"adjustment3\"><prope"
  "rty name=\"upper\">100</property><property name=\"value\">90</property>"
  "<property name=\"step_increment\">1</property><property name=\"page_inc"
  "rement\">10</property></object><object class=\"GtkAdjustment\" id=\"adj"
  "ustment4\"><property name=\"upper\">100</property><property name=\"valu"
  "e\">90</property><property name=\"step_increment\">1</property><propert"
  "y name=\"page_increment\">10</property></object><object class=\"GtkAdju"
  "stment\" id=\"adjustment5\"><property name=\"upper\">100</property><pro"
  "perty name=\"value\">90</property><property name=\"step_increment\">1</"
  "property><property name=\"page_increment\">10</property></object><objec"
  "t class=\"GtkAdjustment\" id=\"adjustment6\"><property name=\"upper\">1"
  "00</property><property name=\"value\">90</property><property name=\"ste"
  "p_increment\">1</property><property name=\"page_increment\">10</propert"
  "y></object><object class=\"XfceTitledDialog\" id=\"main-dialog\"><prope"
  "rty name=\"can_focus\">False</property><property name=\"title\" transla"
  "table=\"yes\">Window Manager Tweaks</property><property name=\"window_p"
  "osition\">center-on-parent</property><property name=\"default_height\">"
  "480</property><property name=\"icon_name\">wmtweaks</property><property"
  " name=\"type_hint\">dialog</property><property name=\"subtitle\" transl"
  "atable=\"yes\">Fine-tune window behaviour and effects</property><child "
  "internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"main-vbox\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><child internal-child=\"action_area\"><object class=\"GtkHB"
  "uttonBox\" id=\"dialog-action_area1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "layout_style\">end</property><child><object class=\"GtkButton\" id=\"bu"
  "tton2\"><property name=\"label\">gtk-help</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">True</property><property name=\"use_stock\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty><property name=\"secondary\">True</property></packing></child><chil"
  "d><object class=\"GtkButton\" id=\"button1\"><property name=\"label\">g"
  "tk-close</property><property name=\"use_action_appearance\">False</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">True</property>"
  "<property name=\"use_stock\">True</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"pack_type\">end</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kNotebook\" id=\"plug-child\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"border_wi"
  "dth\">6</property><child><object class=\"GtkVBox\" id=\"vbox1\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"border_width\">12</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkCheckButton\" id=\"cycl"
  "e_minimum_check\"><property name=\"label\" translatable=\"yes\">S_kip w"
  "indows that have \"skip pager\"\nor \"skip taskbar\" properties set</pr"
  "operty><property name=\"use_action_appearance\">False</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"use_underline\">True</property><property name=\"draw_indicator\">"
  "True</property></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"cycle_hidden_check\"><property name=\"label\" translatable=\"yes\""
  ">_Include hidden (i.e. iconified) windows</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild><child><object class=\"GtkCheckButton\" id=\"cycle_workspaces_check"
  "\"><property name=\"label\" translatable=\"yes\">Cycle _through windows"
  " on all workspaces</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">2</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"cycle_draw_frame\"><property name=\"label\" t"
  "ranslatable=\"yes\">_Draw frame around selected windows while cycling</"
  "property><property name=\"use_action_appearance\">False</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">3</property></packing></child></object></child><child type=\"tab\"><ob"
  "ject class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">C_ycling</property><property name=\"use_un"
  "derline\">True</property></object><packing><property name=\"tab_fill\">"
  "False</property></packing></child><child><object class=\"GtkVBox\" id=\""
  "vbox3\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"border_width\">12</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkCheckBut"
  "ton\" id=\"prevent_focus_stealing_check\"><property name=\"label\" tran"
  "slatable=\"yes\">Activate foc_us stealing prevention</property><propert"
  "y name=\"use_action_appearance\">False</property><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"receives_default\">False</property><property name=\"use_under"
  "line\">True</property><property name=\"draw_indicator\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkCheckButton\" id=\"focus_hint"
  "_check\"><property name=\"label\" translatable=\"yes\">Honor _standard "
  "ICCCM focus hint</property><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">1</property></packing></child><child><object class="
  "\"GtkVBox\" id=\"prevent_focus_stealing_box\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"lab"
  "el11\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"xalign\">0</property><property "
  "name=\"label\" translatable=\"yes\">When a window raises itself:</prope"
  "rty></object><packing><property name=\"expand\">True</property><propert"
  "y name=\"fill\">True</property><property name=\"position\">0</property>"
  "</packing></child><child><object class=\"GtkAlignment\" id=\"alignment2"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"bottom_padding\">6</property><prope"
  "rty name=\"left_padding\">12</property><child><object class=\"GtkVBox\""
  " id=\"vbox14\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"border_width\">6</prope"
  "rty><property name=\"spacing\">6</property><child><object class=\"GtkRa"
  "dioButton\" id=\"activate_action_bring_option\"><property name=\"label\""
  " translatable=\"yes\">_Bring window on current workspace</property><pro"
  "perty name=\"use_action_appearance\">False</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"use_u"
  "nderline\">True</property><property name=\"active\">True</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">0</property></packing></child><child><obje"
  "ct class=\"GtkRadioButton\" id=\"activate_action_switch_option\"><prope"
  "rty name=\"label\" translatable=\"yes\">Switch to win_dow\'s workspace<"
  "/property><property name=\"use_action_appearance\">False</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">False</property><propert"
  "y name=\"use_underline\">True</property><property name=\"active\">True<"
  "/property><property name=\"draw_indicator\">True</property><property na"
  "me=\"group\">activate_action_bring_option</property></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child><chil"
  "d><object class=\"GtkRadioButton\" id=\"activate_action_none_option\"><"
  "property name=\"label\" translatable=\"yes\">Do _nothing</property><pro"
  "perty name=\"use_action_appearance\">False</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"use_u"
  "nderline\">True</property><property name=\"active\">True</property><pro"
  "perty name=\"draw_indicator\">True</property><property name=\"group\">a"
  "ctivate_action_bring_option</property></object><packing><property name="
  "\"expand\">True</property><property name=\"fill\">True</property><prope"
  "rty name=\"position\">2</property></packing></child></object></child></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">2<"
  "/property></packing></child></object><packing><property name=\"position"
  "\">1</property></packing></child><child type=\"tab\"><object class=\"Gt"
  "kLabel\" id=\"label2\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">_Focus</property><property name=\"use_underline\">True</p"
  "roperty></object><packing><property name=\"position\">1</property><prop"
  "erty name=\"tab_fill\">False</property></packing></child><child><object"
  " class=\"GtkVBox\" id=\"vbox4\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"border"
  "_width\">12</property><property name=\"spacing\">6</property><child><ob"
  "ject class=\"GtkHBox\" id=\"hbox1\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"sp"
  "acing\">12</property><child><object class=\"GtkLabel\" id=\"label7\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"xalign\">0</property><property name=\"la"
  "bel\" translatable=\"yes\">Key used to _grab and move windows:</propert"
  "y><property name=\"use_underline\">True</property><property name=\"mnem"
  "onic_widget\">easy_click_combo_box</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkComboBox\" id=\"easy_click_combo_box\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">1</property></p"
  "acking></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"raise_with_any_button_check\"><property name=\"label\" translatabl"
  "e=\"yes\">_Raise windows when any mouse button is pressed</property><pr"
  "operty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"borde"
  "rless_maximize_check\"><property name=\"label\" translatable=\"yes\">Hi"
  "de frame of windows when ma_ximized</property><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">False</property><property name=\"use_underline\">True</prop"
  "erty><property name=\"draw_indicator\">True</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">2</property></packing></child><"
  "child><object class=\"GtkCheckButton\" id=\"restore_on_move_check\"><pr"
  "operty name=\"label\" translatable=\"yes\">Restore original size of max"
  "imi_zed windows when moving</property><property name=\"use_action_appea"
  "rance\">False</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">False</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">3</property></packing></child><child><o"
  "bject class=\"GtkCheckButton\" id=\"tile_on_move_check\"><property name"
  "=\"label\" translatable=\"yes\">Automatically _tile windows when moving"
  " toward the screen edge</property><property name=\"use_action_appearanc"
  "e\">False</property><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"receives_default\">"
  "False</property><property name=\"use_underline\">True</property><proper"
  "ty name=\"draw_indicator\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">4</property></packing></child><child><objec"
  "t class=\"GtkCheckButton\" id=\"snap_resist_check\"><property name=\"la"
  "bel\" translatable=\"yes\">Use _edge resistance instead of window snapp"
  "ing</property><property name=\"use_action_appearance\">False</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"use_underline\">True</property><property name=\"draw_indic"
  "ator\">True</property></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">False</property><property name=\"pos"
  "ition\">5</property></packing></child><child><object class=\"GtkCheckBu"
  "tton\" id=\"urgent_blink\"><property name=\"label\" translatable=\"yes\""
  ">Notify of _urgency by making window\'s decoration blink</property><pro"
  "perty name=\"use_action_appearance\">False</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">False</property><property name=\"use_u"
  "nderline\">True</property><property name=\"draw_indicator\">True</prope"
  "rty></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">False</property><property name=\"position\">6</propert"
  "y></packing></child><child><object class=\"GtkCheckButton\" id=\"repeat"
  "_urgent_blink\"><property name=\"label\" translatable=\"yes\">Keep urge"
  "nt windows _blinking repeatedly</property><property name=\"use_action_a"
  "ppearance\">False</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"receives_de"
  "fault\">False</property><property name=\"use_underline\">True</property"
  "><property name=\"draw_indicator\">True</property></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">False</p"
  "roperty><property name=\"position\">7</property></packing></child><chil"
  "d><object class=\"GtkCheckButton\" id=\"mousewheel_rollup\"><property n"
  "ame=\"label\" translatable=\"yes\">Use mouse wheel on title bar to ro_l"
  "l up the window</property><property name=\"use_action_appearance\">Fals"
  "e</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">8</property></packing></child></object><packing><pr"
  "operty name=\"position\">2</property></packing></child><child type=\"ta"
  "b\"><object class=\"GtkLabel\" id=\"label3\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">_Accessibility</property><property "
  "name=\"use_underline\">True</property></object><packing><property name="
  "\"position\">2</property><property name=\"tab_fill\">False</property></"
  "packing></child><child><object class=\"GtkVBox\" id=\"vbox5\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"border_width\">12</property><property name=\"sp"
  "acing\">6</property><child><object class=\"GtkCheckButton\" id=\"scroll"
  "_workspaces_check\"><property name=\"label\" translatable=\"yes\">Use t"
  "he _mouse wheel on the desktop to switch workspaces</property><property"
  " name=\"use_action_appearance\">False</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">False</property><property name=\"use_underl"
  "ine\">True</property><property name=\"draw_indicator\">True</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkCheckButton\" id=\"toggle_work"
  "spaces_check\"><property name=\"label\" translatable=\"yes\">_Remember "
  "and recall previous workspace\nwhen switching via keyboard shortcuts</p"
  "roperty><property name=\"use_action_appearance\">False</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">1</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"wrap_layout_check\"><property name=\"label\" translatable=\"yes\">"
  "Wrap workspaces depending on the actual desktop _layout</property><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">False</property><property name=\"use_un"
  "derline\">True</property><property name=\"draw_indicator\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">2</property"
  "></packing></child><child><object class=\"GtkCheckButton\" id=\"wrap_cy"
  "cle_check\"><property name=\"label\" translatable=\"yes\">Wrap workspac"
  "es when _the first or the last workspace is reached</property><property"
  " name=\"use_action_appearance\">False</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">False</property><property name=\"use_underl"
  "ine\">True</property><property name=\"draw_indicator\">True</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">3</property></p"
  "acking></child></object><packing><property name=\"position\">3</propert"
  "y></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label4\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "_Workspaces</property><property name=\"use_underline\">True</property><"
  "/object><packing><property name=\"position\">3</property><property name"
  "=\"tab_fill\">False</property></packing></child><child><object class=\""
  "GtkVBox\" id=\"vbox6\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"border_width\">"
  "12</property><property name=\"spacing\">6</property><child><object clas"
  "s=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"xalign\">"
  "0</property><property name=\"label\" translatable=\"yes\">_Minimum size"
  " of windows to trigger smart placement:</property><property name=\"use_"
  "underline\">True</property><property name=\"mnemonic_widget\">placement"
  "_ratio_scale</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment4\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"bottom_padding"
  "\">6</property><property name=\"left_padding\">12</property><child><obj"
  "ect class=\"GtkHBox\" id=\"hbox2\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"spa"
  "cing\">12</property><child><object class=\"GtkLabel\" id=\"label9\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"label\" translatable=\"yes\" comments=\"S"
  "mart placement size\">&lt;i&gt;Small&lt;/i&gt;</property><property name"
  "=\"use_markup\">True</property></object><packing><property name=\"expan"
  "d\">False</property><property name=\"fill\">False</property><property n"
  "ame=\"position\">0</property></packing></child><child><object class=\"G"
  "tkHScale\" id=\"placement_ratio_scale\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "adjustment\">adjustment1</property><property name=\"restrict_to_fill_le"
  "vel\">False</property><property name=\"draw_value\">False</property></o"
  "bject><packing><property name=\"expand\">True</property><property name="
  "\"fill\">True</property><property name=\"position\">1</property></packi"
  "ng></child><child><object class=\"GtkLabel\" id=\"label10\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\" comments=\"Smart pla"
  "cement size\">&lt;i&gt;Large&lt;/i&gt;</property><property name=\"use_m"
  "arkup\">True</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">True</property><property name=\"pos"
  "ition\">2</property></packing></child></object></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">1</property></packing></child>"
  "<child><object class=\"GtkVBox\" id=\"default_placement_box\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"spacing\">6</property><child><object class=\"Gt"
  "kLabel\" id=\"label27\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"xalign\">0</pr"
  "operty><property name=\"label\" translatable=\"yes\">By default, place "
  "windows:</property></object><packing><property name=\"expand\">True</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkAlignment\" "
  "id=\"alignment10\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"bottom_padding\">6<"
  "/property><property name=\"left_padding\">12</property><child><object c"
  "lass=\"GtkVBox\" id=\"vbox18\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"border_"
  "width\">6</property><property name=\"spacing\">6</property><child><obje"
  "ct class=\"GtkRadioButton\" id=\"placement_center_option\"><property na"
  "me=\"label\" translatable=\"yes\">At the c_enter of the screen</propert"
  "y><property name=\"use_action_appearance\">False</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">True</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkRadioButton\" id=\"pla"
  "cement_mouse_option\"><property name=\"label\" translatable=\"yes\">U_n"
  "der the mouse pointer</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"active\">True</property><property name=\"draw_indicator\">True</"
  "property><property name=\"group\">placement_center_option</property></o"
  "bject><packing><property name=\"expand\">True</property><property name="
  "\"fill\">True</property><property name=\"position\">1</property></packi"
  "ng></child></object></child></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">2</property></packing></child></object><pack"
  "ing><property name=\"position\">4</property></packing></child><child ty"
  "pe=\"tab\"><object class=\"GtkLabel\" id=\"label5\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">_Placement</property><proper"
  "ty name=\"use_underline\">True</property></object><packing><property na"
  "me=\"position\">4</property><property name=\"tab_fill\">False</property"
  "></packing></child><child><object class=\"GtkVBox\" id=\"vbox7\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"border_width\">12</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkCheckButton\" id=\"use_"
  "compositing_check\"><property name=\"label\" translatable=\"yes\">_Enab"
  "le display compositing</property><property name=\"use_action_appearance"
  "\">False</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"draw_indicator\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkScrolledWindow\" id=\"use_compositing_box\"><property name="
  "\"visible\">True</property><property name=\"sensitive\">False</property"
  "><property name=\"can_focus\">True</property><property name=\"hscrollba"
  "r_policy\">never</property><property name=\"vscrollbar_policy\">automat"
  "ic</property><child><object class=\"GtkViewport\" id=\"viewport1\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"resize_mode\">queue</property><property na"
  "me=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment3\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"bottom_padding\">6<"
  "/property><property name=\"left_padding\">12</property><child><object c"
  "lass=\"GtkVBox\" id=\"vbox8\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkCheckButton\" id=\"unredirect_ov"
  "erlays_check\"><property name=\"label\" translatable=\"yes\">Display _f"
  "ullscreen overlay windows directly</property><property name=\"use_actio"
  "n_appearance\">False</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"draw_indicator\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkCheckButton\" id=\"sync_to_vblank_check\"><prope"
  "rty name=\"label\" translatable=\"yes\">Synchronize drawing to the _ver"
  "tical blank</property><property name=\"use_action_appearance\">False</p"
  "roperty><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">False</prope"
  "rty><property name=\"use_underline\">True</property><property name=\"dr"
  "aw_indicator\">True</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">1</property></packing></child><child><object class=\"Gtk"
  "CheckButton\" id=\"show_popup_shadow_check\"><property name=\"label\" t"
  "ranslatable=\"yes\">Show shadows under pop_up windows</property><proper"
  "ty name=\"use_action_appearance\">False</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">False</property><property name=\"use_unde"
  "rline\">True</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">True</property><property name=\"position\">2</property></"
  "packing></child><child><object class=\"GtkCheckButton\" id=\"show_dock_"
  "shadow_check\"><property name=\"label\" translatable=\"yes\">Show shado"
  "ws under _dock windows</property><property name=\"use_action_appearance"
  "\">False</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"draw_indicator\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">3</property></packing></child><child><object "
  "class=\"GtkCheckButton\" id=\"show_frame_shadow_check\"><property name="
  "\"label\" translatable=\"yes\">Show shadows under _regular windows</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">4"
  "</property></packing></child><child><object class=\"GtkLabel\" id=\"lab"
  "el12\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"xalign\">0</property><property "
  "name=\"label\" translatable=\"yes\">Opaci_ty of window decorations:</pr"
  "operty><property name=\"use_underline\">True</property><property name=\""
  "mnemonic_widget\">frame_opacity_scale</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">5</property></packing></child><child><"
  "object class=\"GtkAlignment\" id=\"alignment5\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"top_padding\">2</property><property name=\"left_padding\">12<"
  "/property><child><object class=\"GtkHBox\" id=\"hbox3\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><child><object class=\"GtkLabel\" id=\"label17\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;"
  "</property><property name=\"use_markup\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkHScale\" id=\"frame_opacity_scale\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"update_policy\">discontinuous</property><proper"
  "ty name=\"adjustment\">adjustment2</property><property name=\"restrict_"
  "to_fill_level\">False</property><property name=\"draw_value\">False</pr"
  "operty></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">1</proper"
  "ty></packing></child><child><object class=\"GtkLabel\" id=\"label18\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"label\" translatable=\"yes\">&lt;i&gt;O"
  "paque&lt;/i&gt;</property><property name=\"use_markup\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">2</property></"
  "packing></child></object></child></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"position\">6</property></packing></child><child><object class=\""
  "GtkLabel\" id=\"label13\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"xalign\">0</"
  "property><property name=\"label\" translatable=\"yes\">Opacity of _inac"
  "tive windows:</property><property name=\"use_underline\">True</property"
  "><property name=\"mnemonic_widget\">inactive_opacity_scale</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">7</property></pa"
  "cking></child><child><object class=\"GtkAlignment\" id=\"alignment6\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"top_padding\">2</property><property nam"
  "e=\"left_padding\">12</property><child><object class=\"GtkHBox\" id=\"h"
  "box4\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><child><object class=\"GtkLabel\" id=\"label19\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">&lt;i&gt"
  ";Transparent&lt;/i&gt;</property><property name=\"use_markup\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkHScale\" id=\"inactive"
  "_opacity_scale\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"update_policy\">discon"
  "tinuous</property><property name=\"adjustment\">adjustment3</property><"
  "property name=\"restrict_to_fill_level\">False</property><property name"
  "=\"draw_value\">False</property></object><packing><property name=\"expa"
  "nd\">True</property><property name=\"fill\">True</property><property na"
  "me=\"position\">1</property></packing></child><child><object class=\"Gt"
  "kLabel\" id=\"label20\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label\" transl"
  "atable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use"
  "_markup\">True</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">False</property><property name=\""
  "position\">2</property></packing></child></object></child></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">8</property></packing></chi"
  "ld><child><object class=\"GtkLabel\" id=\"label14\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"xalign\">0</property><property name=\"label\" translatabl"
  "e=\"yes\">Opacity of windows during _move:</property><property name=\"u"
  "se_underline\">True</property><property name=\"mnemonic_widget\">move_o"
  "pacity_scale</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">9</property></packing></child><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment7\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"top_padding\">"
  "2</property><property name=\"left_padding\">12</property><child><object"
  " class=\"GtkHBox\" id=\"hbox5\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><child><object class=\""
  "GtkLabel\" id=\"label21\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</property><property nam"
  "e=\"use_markup\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkHScale\" id=\"move_opacity_scale\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"u"
  "pdate_policy\">discontinuous</property><property name=\"adjustment\">ad"
  "justment4</property><property name=\"restrict_to_fill_level\">False</pr"
  "operty><property name=\"draw_value\">False</property></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">1</property></packing></child><chi"
  "ld><object class=\"GtkLabel\" id=\"label22\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property"
  "><property name=\"use_markup\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">2</property></packing></child></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">False</property><property name=\"position\">10</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label15"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"xalign\">0</property><property name"
  "=\"label\" translatable=\"yes\">Opacity of windows during resi_ze:</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "mnemonic_widget\">resize_opacity_scale</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">11</property></packing></child><chil"
  "d><object class=\"GtkAlignment\" id=\"alignment8\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"top_padding\">2</property><property name=\"left_padding\">"
  "12</property><child><object class=\"GtkHBox\" id=\"hbox6\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><child><object class=\"GtkLabel\" id=\"label23\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"label\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&"
  "gt;</property><property name=\"use_markup\">True</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkHScale\" id=\"resize_opacity_scale\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"update_policy\">discontinuous</property><pr"
  "operty name=\"adjustment\">adjustment5</property><property name=\"restr"
  "ict_to_fill_level\">False</property><property name=\"draw_value\">False"
  "</property></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label24"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label\" translatable=\"yes\">&lt;i&"
  "gt;Opaque&lt;/i&gt;</property><property name=\"use_markup\">True</prope"
  "rty></object><packing><property name=\"expand\">False</property><proper"
  "ty name=\"fill\">False</property><property name=\"position\">2</propert"
  "y></packing></child></object></child></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">12</property></packing></child><child><object cla"
  "ss=\"GtkLabel\" id=\"label16\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"xalign\""
  ">0</property><property name=\"label\" translatable=\"yes\">Opacity of p"
  "opup wi_ndows:</property><property name=\"use_underline\">True</propert"
  "y><property name=\"mnemonic_widget\">popup_opacity_scale</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">13</property></pac"
  "king></child><child><object class=\"GtkAlignment\" id=\"alignment9\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"top_padding\">2</property><property name"
  "=\"left_padding\">12</property><child><object class=\"GtkHBox\" id=\"hb"
  "ox7\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><child><object class=\"GtkLabel\" id=\"label25\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label\" translatable=\"yes\">&lt;i&gt;"
  "Transparent&lt;/i&gt;</property><property name=\"use_markup\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty></packing></child><child><object class=\"GtkHScale\" id=\"popup_opa"
  "city_scale\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"update_policy\">discontinuo"
  "us</property><property name=\"adjustment\">adjustment6</property><prope"
  "rty name=\"restrict_to_fill_level\">False</property><property name=\"dr"
  "aw_value\">False</property></object><packing><property name=\"expand\">"
  "True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label26\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_mark"
  "up\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">2</property></packing></child></object></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">14</property></packing></child><"
  "/object></child></object></child></object></child></object><packing><pr"
  "operty name=\"expand\">True</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">1</property></packing></child></objec"
  "t><packing><property name=\"position\">5</property></packing></child><c"
  "hild type=\"tab\"><object class=\"GtkLabel\" id=\"label6\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\">C_ompositor</property"
  "><property name=\"use_underline\">True</property></object><packing><pro"
  "perty name=\"position\">5</property><property name=\"tab_fill\">False</"
  "property></packing></child></object><packing><property name=\"expand\">"
  "True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object></child><action-widge"
  "ts><action-widget response=\"-11\">button2</action-widget><action-widge"
  "t response=\"0\">button1</action-widget></action-widgets></object></int"
  "erface>"
};

static const unsigned tweaks_dialog_ui_length = 44026u;

